var ERROR_BATTLE_TIME_NOT_TO = 1;
var ERROR_ROLE_DEAD = 1042;

var ITEM_SELL_SUCCESS = 1;						//物品出售成功
var ITEM_SELL_ERROR_LOCKED = 1043;				//物品被锁定
var ITEM_SELL_ERROR_NOT_ENOUGH = 1044;			//指定数量超过当前持有量
var ITEM_SELL_ERROR_NOT_EXIST = 1045;			//指定物品不存在
var ITEM_SELL_ERROR_NO_PARAM = 1046;			//参数不正确

var ALCHEMY_LEARN_SUCCESS = 1;					//学习配方成功
var ALCHEMY_LEARN_ERROR_LOCKED = 1043;			//物品被锁定
var ALCHEMY_LEARN_ERROR_NOT_ENOUGH = 1044;		//指定数量超过当前持有量
var ALCHEMY_LEARN_ERROR_NOT_EXIST = 1045;		//指定物品不存在
var ALCHEMY_LEARN_ERROR_NO_PARAM = 1046;		//参数不正确
var ALCHEMY_LEARN_ERROR_EXIST = 1047;			//指定配方已经学习

var ALCHEMY_INFO_SUCCESS = 1;					//显示配方成功
var ALCHEMY_INFO_ERROR_NO_PARAM = 1046;			//参数不正确
var ALCHEMY_INFO_ERROR_NOT_EXIST = 1047;		//指定配方不存在

var ALCHEMY_BUILD_SUCCESS = 1;					//显示配方成功
var ALCHEMY_BUILD_ERROR_NO_PARAM = 1046;		//参数不正确
var ALCHEMY_BUILD_ERROR_NOT_EXIST = 1047;		//指定配方不存在
var ALCHEMY_BUILD_ERROR_NOT_ENOUGH = 1044;		//指定配方材料不足
var ALCHEMY_BUILD_ERROR_MAX_QUEUE = 1048		//队列已满

var ALCHEMY_RECEIVE_SUCCESS = 1;				//显示配方成功
var ALCHEMY_RECEIVE_ERROR_NO_PARAM = 1046;		//参数不正确
var ALCHEMY_RECEIVE_ERROR_NOT_EXIST = 1047;		//指定配方不存在